# Usa la imagen oficial de MySQL desde Docker Hub
FROM mysql:latest

# Variables de entorno para configurar la base de datos
ENV MYSQL_DATABASE=proyecto
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin

# El puerto que estará expuesto por el contenedor (por defecto es 3306)
EXPOSE 3306